global using IdeaTech.CandyBox;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using ModelContextProtocol.Client;
global using ModelContextProtocol.Protocol;
global using ModelContextProtocol.Server;
global using System.Net.Http.Headers;
global using System.Text.Json;
